engineStrict: true

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: false

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
patchedDependencies:
  app-builder-lib@26.15.3: patches/app-builder-lib@26.15.3.patch
