packages:
  - "."

overrides:
  '@pierre/diffs>shiki': '4.3.1'

allowBuilds:
  '@tailwindcss/oxide': true
  electron: true
  electron-winstaller: false
  esbuild: false
  msgpackr-extract: false

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "effect@4.0.0-beta.106"
