packages:
  - src/apps/*
  - src/contracts

engineStrict: true

allowBuilds:
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: false

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

catalog:
  drizzle-kit: 1.0.0-rc.5-ab785fc
  drizzle-orm: 1.0.0-rc.5-169397b
  effect: 4.0.0-rc.110
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10
  vite-plus: 0.2.9
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
