export const SidecarOp = {
  openRepo: 'open-repo',
  closeRepo: 'close-repo',
  getBranches: 'get-branches',
  getLocalBranches: 'get-local-branches',
  getRemoteRefs: 'get-remote-refs',
  getStatus: 'get-status',
  stageFile: 'stage-file',
  unstageFile: 'unstage-file',
  stageAll: 'stage-all',
  unstageAll: 'unstage-all',
  getDiff: 'get-diff',
  stageHunk: 'stage-hunk',
  unstageHunk: 'unstage-hunk',
  fetchRepo: 'fetch-repo',
  pushRepo: 'push-repo',
  pullRepo: 'pull-repo',
  getLog: 'get-log',
  checkoutRef: 'checkout-ref',
  createBranch: 'create-branch',
  deleteBranch: 'delete-branch',
  renameBranch: 'rename-branch',
  mergeBranch: 'merge-branch',
  resetToCommit: 'reset-to-commit',
  revertCommit: 'revert-commit',
  cherryPick: 'cherry-pick',
  createTag: 'create-tag',
  deleteTag: 'delete-tag',
  stashList: 'stash-list',
  stashPush: 'stash-push',
  stashApply: 'stash-apply',
  stashPop: 'stash-pop',
  stashDrop: 'stash-drop',
  discardChanges: 'discard-changes',
  discardAll: 'discard-all',
  scanForRepos: 'scan-for-repos'
} as const

export type SidecarOpName = (typeof SidecarOp)[keyof typeof SidecarOp]
